### PR TITLE
Edited Product Backlog for Sprint1

### PR DESCRIPTION
**Pull request by pajayreddy**
Added User Stories with pointed tasks, and also added priorities and points to the respective tasks.

### CODE REVIEW

**Comment by Dorayya62** [comment]
I think it would be better to add total story points beside the User Story on the top to instantly understand the complexity of the User Story. Rest all looks good

**Comment by pajayreddy** [comment]
Ya, it is a good idea, let me put it.

**Comment by pajayreddy** [comment]
Added total story points, please review and merge.

**Comment by Dorayya62** [comment]
Ya, now it looks good

**Pull request merged**
