### PR TITLE
Added a contract to program ToDoc class

### PR DESCRIPTION
**Pull request by pajayreddy**
Added a contract with Invariant Assertion, pre-conditions, and post-condition to code ToDoc class which has the functionality to convert a PDF into a WORD doc.

### CODE REVIEW

**Comment by Dorayya62** [comment]
After going through contract I need a small clarification, will that method convertToDoc() creates a new converted WORD doc and saves it, or it replaces the existing PDF with the word doc.

**Comment by pajayreddy** [comment]
It replaces the PDF with word doc.

**Comment by Dorayya62** [comment]
Instead of touching the original PDF, can't you create a new converted word doc and save it in the same path.?, is it possible to do?

**Comment by pajayreddy** [comment]
Ya, can do that by making some changes in the code, let me update the contract as per that.

**Comment by pajayreddy** [comment]
Made changes in the contract so that the convert to doc functionality does not replace the original PDF but creates a new one.

**Pull request merged**
